export {default as Login} from "./Login/Login"
export {default as Register} from "./RegisterPage/Register"
export {default as EmailVerificationSuccess} from "./RegisterPage/EmailVerificationSuccess"
export {default as HomePage} from "./Homepage/Homepage"
export {default as CarPage} from "./CarPage/CarPage"
export {default as BrandPage} from "./BrandPage/BrandPage"
export {default as OurTeamPage} from "./OurTeamPage/OurTeamPage"
export {default as ContactPage} from "./ContactPage/ContactPage"
export {default as ProfilePage} from "./ProfilePage/ProfilePage"
export {default as ResetPassword} from "./ResetPasswordPage/ResetPassword"
export {default as ChangePassword} from "./ChangePasswordPage/ChangePassword"
export {default as SuccessPage} from "./MessagePages/SuccessPage"


export {default as ReservationPage} from "./ReservationPage/ReservationPage"

export {default as NotFoundPage} from "./NotFoundPage/PageNotFound"
export {default as Online} from "./PaymentPage/Online"
export {default as Cash} from "./PaymentPage/Cash"
export {default as BankTransfer} from "./PaymentPage/BankTransfer"
export {default as Successful} from "./PaymentPage/payment-response/Successful"
export {default as Failed} from "./PaymentPage/payment-response/Failed"


export {default as CookiePolicy} from "./LegalPages/CookiePolicy"
export {default as CopyrightNotice} from "./LegalPages/CopyrightNotice"
export {default as CRandComplaintProcedures} from "./LegalPages/CRandComplaintProcedures"
export {default as InsuranceInformation} from "./LegalPages/InsuranceInformation"
export {default as LegalNotices} from "./LegalPages/LegalNotices"
export {default as PrivacyPolicy} from "./LegalPages/PrivacyPolicy"
export {default as RentalAgreement} from "./LegalPages/RentalAgreement"
export {default as RentalConditions} from "./LegalPages/RentalConditions"
export {default as SecurityNotices} from "./LegalPages/SecurityNotices"
export {default as TermsAndConditions} from "./LegalPages/TermsAndConditions"
export {default as TermsOfUse} from "./LegalPages/TermsOfUse"
export {default as VehicleConditionReports} from "./LegalPages/VehicleConditionReports"

