export {default as Login} from "./Login/Login"
export {default as Register} from "./RegisterPage/Register"
export {default as HomePage} from "./Homepage/Homepage"
export {default as CarPage} from "./CarPage/CarPage"
export {default as BrandPage} from "./BrandPage/BrandPage"
export {default as AboutUsPage} from "./AboutUsPage/AboutUsPage"
export {default as ContactPage} from "./ContactPage/ContactPage"
export {default as PrivacyPolicy} from "./LegalPages/PrivacyPolicy"