

const bookingCars = [
  {
    id: "01",
    carName: "Porshe 718 Cayman S",
    category: "Audi",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "02",
    carName: "Porshe 718 Cayman S",
    category: "Toyota",
    type: "Manual",
    groupSize: 4,
    rentPrice: 59,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "03",
    carName: "Porshe 718 Cayman S",
    category: "Bmw",
    type: "Manual",
    groupSize: 4,
    rentPrice: 109,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "04",
    carName: "Porshe 718 Cayman S",
    category: "Coupe",
    type: "Manual",
    groupSize: 4,
    rentPrice: 99,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "05",
    carName: "Porshe 718 Cayman S",
    category: "Bmw",
    type: "Manual",
    groupSize: 4,
    rentPrice: 109,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "06",
    carName: "Porshe 718 Cayman S",
    category: "Toyota",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "07",
    carName: "Porshe 718 Cayman S",
    category: "Audi",
    type: "Manual",
    groupSize: 4,
    rentPrice: 89,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "08",
    carName: "Porshe 718 Cayman S",
    category: "Toyota",
    type: "Manual",
    groupSize: 4,
    rentPrice: 59,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
  {
    id: "09",
    carName: "Porshe 718 Cayman S",
    category: "Bmw",
    type: "Manual",
    groupSize: 4,
    rentPrice: 109,
    imgUrl: "assets/images/bmw320-kirmizi.png",
  },
];

export default bookingCars;